- name: url-mixtcha
  extra_params:
    api_base: "https://api.mixtcha.com"
    api_key: "sk-mix-1234yourkeyhere"
    model: "openai/https://raw.githubusercontent.com/mixtcha/mixtcha/refs/heads/deepseek-aider/experiments/deepseek-aider/multiple-hats.yaml"
    litellm_provider: "openai"

- name: direct-mixtcha
  extra_params:
    api_base: "https://api.mixtcha.com"
    api_key: "sk-mix-1234yourkeyhere"
    model: "openai/{delimiter: [<option>, </option>], layers: [{models: [deepseek/deepseek-chat, deepseek/deepseek-chat],
      systemPrompts: ['think through the problem like a test engineer, from the end
          to the beginning', 'think through the problem from first principles, step
          by step, from the beginning'], type: parallel}, {model: deepseek/deepseek-chat,
      prompt: 'Multiple answers were provided between <option> tags. Please synthesize
        them into a single, high-quality response. Do not assume that I have seen
        these responses. Consider all perspectives and create a comprehensive answer
        that leverages all approaches. Think step-by-step before providing your final
        answer.', type: aggregator}], messageMode: inline}"
    litellm_provider: "openai"

- name: single-model
  extra_params:
    api_base: "https://api.mixtcha.com"
    api_key: "sk-mix-1234yourkeyhere"
    model: "openai/deepseek/deepseek-chat"
    litellm_provider: "openai"